stages:  
  - assemble       
  - test
  - sonarQube
 

assemble:
  stage: assemble
  script: 
    - gradle assemble


test:       
  stage: test
  script:
    - gradle test

sonarQube: 
 stage: sonarQube
 script:
 - ./gradlew sonarqube -D "sonar.projectKey=back-end-cinema-system" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=31aa55b3231133aa6b48d5f8f633d2ef38f15a82"

    

